cnpj_data_lakehouse:
  target: dev
  outputs:
    dev:
      type: duckdb            
      path: "{{ env_var('DBT_DB_PATH', default='/opt/airflow/duckdb/cnpj_data_lakehouse_2026_08.duckdb') }}"
      threads: 1
            
      extensions:
        - httpfs
        - aws

      config_options:
        temp_directory: '/opt/airflow/duckdb/tmp'

      settings:
        max_memory: '13GB'
        memory_limit: '13GB'
        max_temp_directory_size: '100GB'
        preserve_insertion_order: false
        s3_url_style: 'path'
        s3_endpoint: 'minio:9000'
        s3_use_ssl: false
        s3_region: 'us-east-1'        
        s3_access_key_id: "{{ env_var('MINIO_ROOT_USER', default='minioadmin') }}"      
        s3_secret_access_key: "{{ env_var('MINIO_ROOT_PASSWORD', default='minioadmin') }}"