version: 2

models:
  - name: gold_cnaes
    description: "Tabela oficial de Classificação Nacional de Atividades Econômicas (CNAE) da Receita Federal."
    columns:
      - name: codigo_cnae
        description: "Código numérico da atividade econômica (Ex: 6204000)."
        data_tests:
          - unique
          - not_null
      
      - name: descricao_cnae
        description: "Nome descritivo da atividade (Ex: Consultoria em tecnologia da informação)."
        data_tests:
          - not_null